name: Deployment to ISTE Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}       # VPS IP address
          username: ${{ secrets.USERNAME }}     # VPS username (e.g., ubuntu, root)
          key: ${{ secrets.VPS_SSH_KEY }}       # Private SSH key stored as a GitHub secret
          script: |
            # Add GitHub's SSH key to known hosts to prevent 'Host key verification failed'
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Pull changes and rebuild
            cd /home/iste/iste-projects/pwa_prodyogiki25
            git remote set-url origin git@github.com:istenith/pwa_prodyogiki25.git
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build

            # Restart PM2 with specific working directory
            pm2 restart pwa-app || pm2 start npm --name "pwa-app" -- start
